# This corresponds to the main random-walk model in the paper
name: Random-walk model
id: null
type: bayes
inference:
  state_space:
    hmean: "true"
    hsd: "true"
    hvol:
      type: discrete
      values: [10, 30]
  dynamics:
    hmean:
      type: random_walk
    hsd: "true"
    hvol:
      type: change_point
      p_cp: 0.0625 # 1/16
bet_fun: max_reward
prob_updt:
  fun_type: truncnorm
  fun_params: [0, 8]