"""
Plot the observation/hidden state sequences generated by the generative model of
the given agent model.

Note: These plots are outdated
"""

import argparse
import infer_pred_model
import matplotlib.pyplot as plt
import numpy as np
import os.path as op
import utils

def main(args):
    output_dir = op.join(utils.output.DIR, "sequences")
    utils.output.create_dir_if_needed(output_dir)
    utils.plot.setup_mpl_style()

    # Load the generative model assumed by the inference model of the given task model
    task_config = utils.config.load_config_at_path_with_default_task_config(args.task_config_path)
    model_config = utils.config.load_config_at_path_with_default_model_config(args.model_config_path)
    config = utils.config.create_joint_config(task_config, model_config)
    model = infer_pred_model.get_model(config)
    gen_model = model.inference_model.generative_model
    nobs = task_config["nobs"]
    for seed in args.seeds:
        # Generate sequence
        np.random.seed(seed)
        obs, hid = gen_model.generate(nobs)
        ndims = hid.shape[1]
        # Plot sequence
        figsize = (utils.plot.PAPER_CONTENT_WIDTH,
                 utils.plot.PAPER_CONTENT_WIDTH/3*ndims)
        fig, axes = plt.subplots(figsize=figsize,
            nrows=ndims)
        if ndims == 1:
            axes = [axes]
        t = np.arange(nobs)+1
        axes[-1].set_xlabel("Observation number")
        row = 0
        utils.plot.plot_seq_common(axes[row], t, [
            ("obs", dict(y=obs)),
            ("hmean", dict(y=hid[:, 0]))])
        axes[row].set_ylabel("Observation/Hidden mean")
        if gen_model.hidstate_space.has_hsd:
            row += 1
            axes[row].plot(t, hid[:, gen_model.hidstate_space.hsd_dim], '--',
                color=utils.plot.COLORS_GRAY[4])
            axes[row].set_ylabel("Stochasticity")
        if gen_model.hidstate_space.has_hvol:
            row += 1
            axes[row].plot(t, hid[:, gen_model.hidstate_space.hvol_dim], '--',
                color=utils.plot.COLORS_GRAY[4])
            axes[row].set_ylabel("Volatility")
        fig.suptitle(f"Generative model: {model.name}")
        # Save figure
        prefix = "gen_model_sequence"
        figname = utils.output.name_with_params(prefix,
            ["config", "seed"], [config["id"], f"{seed:02d}"])
        ext = "png"
        figpath = utils.output.get_path(output_dir, figname, ext)
        utils.output.save_figure(fig, figpath)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-tcp", "--task_config_path", default=None)
    parser.add_argument("-mcp", "--model_config_path", default=None)
    parser.add_argument("-s", "--seeds", nargs="+", default=[0], type=(int))
    args = parser.parse_args()
    main(args)
